//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInventarios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class inventariosEntities : DbContext
    {
        public inventariosEntities()
            : base("name=inventariosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<inventario> inventario { get; set; }
        public virtual DbSet<materiales> materiales { get; set; }
        public virtual DbSet<tipo> tipo { get; set; }
        public virtual DbSet<tipoestado> tipoestado { get; set; }
    }
}
