//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventario
    {
        public int idinventario { get; set; }
        public int idMaterial { get; set; }
        public int cantidad { get; set; }
        public int idTipoEstado { get; set; }
    
        public virtual materiales materiales { get; set; }
        public virtual tipoestado tipoestado { get; set; }
    }
}
